# Generated by Django 5.2 on 2025-04-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '__first__'),
        ('appointments', '0002_rename_appointment_appointments'),
        ('core', '0001_initial'),
        ('results', '__first__'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Usuarios',
        ),
    ]
